version: "2"

run:
  timeout: 5m
  # skip-dirs:
  #   - vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - prealloc
    - misspell
    - bodyclose

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
